#!/usr/bin/python

import sys
import dbus

bus = dbus.SessionBus()
client = dbus.Interface(bus.get_object("org.openobex.client", "/"),
							"org.openobex.Client")

if (len(sys.argv) < 4):
	print "Usage: %s <device> <clientfile> <file>" % (sys.argv[0])
	sys.exit(1)

client.ExchangeBusinessCards({ "Destination": sys.argv[1] },
						sys.argv[2], sys.argv[3])
