#!/usr/bin/python

import sys
import dbus

bus = dbus.SessionBus()
client = dbus.Interface(bus.get_object("org.openobex.client", "/"),
					"org.openobex.Client")

if (len(sys.argv) < 2):
	print "Usage: %s <device> [target]" % (sys.argv[0])
	sys.exit(1)

if (len(sys.argv) == 3):
	dict = {"Destination": sys.argv[1],
		"Target": sys.argv[2]}
else:
	dict = {"Destination": sys.argv[1]}

print client.GetCapabilities(dict)
