#!/bin/sh

if [ -f config.status ]; then
	make maintainer-clean
fi

./bootstrap && \
    ./configure --enable-maintainer-mode \
		--enable-debug \
		--prefix=/usr \
		--libexec=/usr/lib/obex \
		--mandir=/usr/share/man \
		--sysconfdir=/etc \
		--with-messages=dummy \
		--with-phonebook=dummy \
		--enable-usb \
		--enable-pcsuite $*
